import os
from collections import defaultdict
import uuid

from PySide.QtWidgets import QInputDialog, QMessageBox, QFileDialog

import FreeCAD as App
import FreeCADGui as Gui
import TechDrawGui
import TechDraw

from freecad.plume.pl_tools import UIPATH, ICONPATH, TRANSLATIONSPATH, translate
from freecad.plume.utils.widgets import open_or_create_directory, InitializePlumeObjectDialog
from freecad.plume.utils.fc_utils import create_thumbnail, is_fastener, get_fastener_name, get_ipn_suggestion

from freecad.plume.tools.Common import CommonCommand, catch_svn

from freecad.frameforge.create_bom import (
    group_links,
    group_profiles,
    make_bom,
    make_cut_list,
    traverse_assembly,
)

class InitializePlumeObjectCommand(CommonCommand):
    def GetResources(self):
        return {
            "Pixmap": os.path.join(ICONPATH, "initialize-object.svg"),
            "MenuText": translate("Plume", "Initialize a Plume object"),
            "Accel": "P, I",
            "ToolTip": translate(
                "Plume",
                "<html><head/><body><p><b>Initialize a Plume Object</b> \
                    <br><br> \
                    Select an Object in the tree and then launch the tool \
                    </p></body></html>",
            ),
        }

    def IsActive(self):
        sel = Gui.Selection.getSelection()
        if len(sel) == 1:
            obj = sel[0]
            if not hasattr(obj, "PlumeIPN"):
                return True

        return False

    def Activated(self):
        sel = Gui.Selection.getSelection()
        obj = sel[0]

        part_type = "MechanicalPart"
        version, revision = "", ""

        pi = self.inventree()
        all_parts = pi.get_parts()
        all_ipns = list(set([p.IPN for p in all_parts]))

        fastener = is_fastener(obj)
        ipn_suggestion = get_fastener_name(obj) if fastener else get_ipn_suggestion(obj)

        # get IPN schematic and 
        repo_config = self.config()
        if repo_config['plume_ipn_autogenerated']:  # does it make sense ??? one could use db only for autogenerated, ie be able to link
            if QMessageBox.question(
                    None, 
                    "Create new Part", 
                    'Do you want to create new Part in DB?') == QMessageBox.StandardButton.Yes:
                diag_ret = True
                ipn = str(uuid.uuid4())
                new_ipn = True
                db_link = False

            else:
                diag_ret, db_link, new_ipn, ipn, part_type = InitializePlumeObjectDialog.get_plume_object_infos(all_ipns, existing_only=True, part_type=part_type)

        else:
            diag_ret, db_link, new_ipn, ipn, part_type = InitializePlumeObjectDialog.get_plume_object_infos(all_ipns, force_db_link=fastener, ipn_suggestion=ipn_suggestion, part_type=part_type)

        if not diag_ret:
            self.log('cancelled by user')
            return

        if not new_ipn:
            ver_revs = [p.revision for p in pi.get_parts(ipn=ipn)]
            verrev, ok = QInputDialog.getItem(None, "Choose version", f"Choose version/revision for {ipn}", ver_revs)
            if not ok:
                self.log('cancelled by user')
                return

            version, revision = verrev.split('.')


        if QMessageBox.question(
                None, 
                "Confirm creating new Part", 
                f'Do you confirm this new part : {ipn=}, {new_ipn=}, {db_link=}?') == QMessageBox.StandardButton.No:
            self.log('cancelled by user')
            return

        if part_type not in ["MechanicalPart", "MechanicalAssembly", "FrameForgeAssembly"]:
            self.log('Bad part type')
            return



        obj.addProperty(
            "App::PropertyString",
            "PlDescription",
            "Plume",
            "Description",
        ).PlDescription = ""

        obj.addProperty(
            "App::PropertyString",
            "PlVersion",
            "Plume",
            "Version",
        ).PlVersion = version
        obj.addProperty(
            "App::PropertyString",
            "PlRevision",
            "Plume",
            "Revision",
        ).PlRevision = revision
        if db_link:
            obj.PlVersion = "#"
            obj.PlRevision = "#"


        obj.addProperty(
            "App::PropertyEnumeration",
            "PlType",
            "Plume",
            "Plume Type",
        ).PlType = ["MechanicalPart", "MechanicalAssembly", "FrameForgeAssembly"]
        obj.PlType = part_type

        obj.addProperty(
            "App::PropertyEnumeration",
            "PlSourcing",
            "Plume",
            "Sourcing of the Part Object",
        ).PlSourcing = ['Manufactured', 'Purchased']

        obj.addProperty(
            "App::PropertyBool",
            "PlVirtual",
            "Plume",
            "Virtual Object : Software, Licence, Process ...",
        ).PlVirtual = False

        obj.addProperty(
            "App::PropertyBool",
            "PlDatabaseLink",
            "Plume",
            "",
        ).PlDatabaseLink = db_link
        obj.setEditorMode("PlDatabaseLink", 1)  # user doesn't change !


        # 0 -- Prop_None, No special property attribute
        # 1 -- Prop_ReadOnly, Property is read-only in the editor
        # 2 -- Prop_Transient, Property won't be saved to file
        # 4 -- Prop_Hidden, Property won't appear in the editor
        # 8 -- Prop_Output, Modified property doesn't touch its parent container
        # 16 -- Prop_NoRecompute, Modified property doesn't touch its container for recompute
        # 32 -- Prop_NoPersist, Property won't be saved to file at all
        # obj.addProperty("App::PropertyString", "MyCustomProperty", "", "", 8)
        obj.addProperty(
            "App::PropertyString",
            "SvnStatus",
            "Plume",
            "SVN Status of the related file",
            1 + 2 + 8 + 16
        ).SvnStatus = ""

        obj.addProperty(
            "App::PropertyString",
            "SvnSwitched",
            "Plume",
            "SVN Switch to another file",
            1 + 2 + 8 + 16
        ).SvnSwitched = ""

        obj.addProperty(
            "App::PropertyStringList",
            "ExportedSteps",
            "Plume",
            "ExportedSteps",
        ).ExportedSteps = []
        obj.setEditorMode("ExportedSteps", 1)  # user doesn't change !

        obj.addProperty(
            "App::PropertyStringList",
            "ExportedTechDrawPages",
            "Plume",
            "ExportedTechDrawPages",
        ).ExportedTechDrawPages = []
        obj.setEditorMode("ExportedTechDrawPages", 1)  # user doesn't change !

        obj.addProperty(
            "App::PropertyStringList",
            "ExportedCNCJobs",
            "Plume",
            "ExportedCNCJobs",
        ).ExportedCNCJobs = []
        obj.setEditorMode("ExportedCNCJobs", 1)  # user doesn't change !

        obj.addProperty(
            "App::PropertyStringList",
            "ExportedDXFs",
            "Plume",
            "ExportedDXFs",
        ).ExportedCNCJobs = []
        obj.setEditorMode("ExportedDXFs", 1)  # user doesn't change !

        obj.addProperty(
            "App::PropertyString",
            "PlumeIPN",
            "Plume",
            "Plume/Inventree Internal Part Number",
        ).PlumeIPN = ipn
        obj.setEditorMode("PlumeIPN", 1)  # user doesn't change !



class EditExportedObjectsCommand(CommonCommand):
    def GetResources(self):
        return {
            "Pixmap": os.path.join(ICONPATH, "edit-exported.svg"),
            "MenuText": translate("Plume", "Edit Exported Objects"),
            "Accel": "P, I",
            "ToolTip": translate(
                "Plume",
                "<html><head/><body><p><b>Edit exported Plume Object</b> \
                    <br><br> \
                    Select the Plume Object in the tree, and related Group of objects or Objects and then launch the tool \
                    </p></body></html>",
            ),
        }

    @catch_svn
    def IsActive(self):
        sel = Gui.Selection.getSelection()
        if len(sel) > 0:
            if hasattr(sel[0], "PlumeIPN"):
                svn = self.svn()
                root = sel[0]
                root_path = root.Document.FileName
                if not (\
                    svn.is_in_repository(root_path) and \
                    svn.is_trunk_path(root_path) and \
                    # svn.is_path_clean(root_path) and \
                    (not svn.is_path_switched(svn.get_rel_path(root_path))) and \
                    (not svn.is_path_external(svn.get_rel_path(root_path))) and \
                    svn.is_path_locked(svn.get_rel_path(root_path))
                ):
                    return False

                return True

        return False

    def Activated(self):
        sel = Gui.Selection.getSelection()
        root_obj = sel.pop(0)

        cat, ok = QInputDialog.getItem(None, "Add to", "Add objects to : ", ['ExportedSteps', 'ExportedTechDrawPages', 'ExportedDXFs', 'ExportedCNCJobs'])
        if ok:
            setattr(root_obj, cat, [o.Name for o in sel])


class BuildExportedFilesCommand(CommonCommand):
    def GetResources(self):
        return {
            "Pixmap": os.path.join(ICONPATH, "build-exported.svg"),
            "MenuText": translate("Plume", "Build exported files"),
            "Accel": "P, I",
            "ToolTip": translate(
                "Plume",
                "<html><head/><body><p><b>Build exported files (STEP, PDF, etc) for a given object</b> \
                    <br><br> \
                    Select the Plume Object in the tree, and fire \
                    </p></body></html>",
            ),
        }

    @catch_svn
    def IsActive(self):
        sel = Gui.Selection.getSelection() # here, the object is needed for future use
        if len(sel) != 1:
            return False

        obj = sel[0]
        if not hasattr(obj, "PlumeIPN"):
            return False

        if obj.PlDatabaseLink or obj.PlVersion == "" or obj.PlRevision == "":
            return False

        root_path = obj.Document.FileName

        svn = self.svn()
        if svn is None:
            return False

        if not (\
            svn.is_in_repository(root_path) and \
            svn.is_release_path(root_path) and \
            svn.is_path_clean(root_path) and \
            (not svn.is_path_external(svn.get_rel_path(root_path))) and \
            (not svn.is_path_switched(svn.get_rel_path(root_path))) and \
            (not svn.is_path_locked(svn.get_rel_path(root_path)))
        ):
            return False

        return True

    def Activated(self):
        def recursive_scan(group, path=""):
            if path == "":
                path = group.Label

            if group.TypeId == 'App::DocumentObjectGroup':
                for obj in group.Group:
                    if obj.TypeId == 'App::DocumentObjectGroup':
                        yield from recursive_scan(obj, path=path + "/" + obj.Label)
                    
                    else:
                        print(" - ", path, obj.Label)
                        yield (path, obj)
            

        svn = self.svn()

        sel = Gui.Selection.getSelection()
        root_obj = sel[0]

        abs_root_path = root_obj.Document.FileName
        dest = self.get_export_dir(abs_root_path)
        if dest is None:
            self.log('no dest for export !')
            return
        

        # prepare folder
        dest_root_dir = os.path.split(dest)[0]
        if not os.path.isdir(dest_root_dir):
            os.makedirs(dest_root_dir, exist_ok=True)
            svn.add(dest_root_dir)
            svn.commit(f"Add export folder {dest_root_dir}", [dest_root_dir])

        os.makedirs(dest, exist_ok=False) # force housekeeping, should be handled in a better way (TODO)


        # main shape
        root_obj.Shape.exportStep(os.path.join(dest, root_obj.Label + ".step"))

        # exported objects (plans, etc)
        categories = ['ExportedSteps', 'ExportedTechDrawPages', 'ExportedDXFs', 'ExportedCNCJobs']
        for exp_objects, cat in [(getattr(root_obj, c), c)for c in categories]:
            for eo_name in exp_objects:
                eo = root_obj.Document.getObject(eo_name)
                for (subpath, obj) in recursive_scan(eo):
                    file_dirpath = os.path.join(dest, subpath)
                    os.makedirs(file_dirpath, exist_ok=True)

                    file_path = os.path.join(file_dirpath, obj.Label)

                    match cat:
                        case 'ExportedSteps':
                            if hasattr(obj, "Shape"):
                                file_path += ".step"
                                obj.Shape.exportStep(file_path)
                                App.Console.PrintMessage(f'Exporting {file_path}\n')
                            else:
                                App.Console.PrintError(f"obj has no Shape: {obj.Label}\n")

                        case 'ExportedTechDrawPages':
                            if obj.TypeId == "TechDraw::DrawPage":
                                file_path += ".pdf"
                                TechDrawGui.exportPageAsPdf(obj, file_path)
                            else:
                                App.Console.PrintError(f"obj is not a TechDraw: {obj.Label}\n")

                        case 'ExportedDXFs':
                            if obj.TypeId == "TechDraw::DrawPage":
                                file_path += ".dxf"
                                TechDraw.writeDXFPage(obj, file_path)
                            else:
                                App.Console.PrintError(f"obj is not a TechDraw: {obj.Label}\n")

                        case 'ExportedCNCJobs':
                            pass # TODO...

        # TODO : BOM, CSV ?

        # Thumbnail 
        create_thumbnail(root_obj.Document.FileName, dest)




class PublishPartCommand(CommonCommand):
    def GetResources(self):
        return {
            "Pixmap": os.path.join(ICONPATH, "publish-part.svg"),
            "MenuText": translate("Plume", "Publish selected Plume Part"),
            "Accel": "P, I",
            "ToolTip": translate(
                "Plume",
                "<html><head/><body><p><b>Publish a plume part</b> \
                    1. Check if all sub part exists in Inventree \
                    2. Commit export folder if configured \
                    3. Create inventree Part \
                    <br><br> \
                    Select the Plume Object in the tree, and fire \
                    </p></body></html>",
            ),
        }

    @catch_svn
    def IsActive(self):
        sel = Gui.Selection.getSelection() # here, the object is needed for future use
        if len(sel) != 1:
            return False

        obj = sel[0]
        if not hasattr(obj, "PlumeIPN"):
            return False

        if obj.PlVersion == "" or obj.PlRevision == "":
            return False

        root_path = obj.Document.FileName

        svn = self.svn()
        if svn is None:
            return False

        # Allows to create a Inventree Part if it is a DB Linked only. 
        # No files will be commited
        if obj.PlDatabaseLink: 
            return True

        if not (\
            svn.is_in_repository(root_path) and \
            svn.is_release_path(root_path) and \
            # svn.is_path_clean(root_path) and \
            (not svn.is_path_external(svn.get_rel_path(root_path))) and \
            (not svn.is_path_switched(svn.get_rel_path(root_path))) and \
            (not svn.is_path_locked(svn.get_rel_path(root_path)))
        ):
            return False

        return True

    def Activated(self):
        svn = self.svn()
        repo_config = self.config()

        sel = Gui.Selection.getSelection()
        root_obj = sel[0]

        abs_root_path = root_obj.Document.FileName
        dest = self.get_export_dir(abs_root_path)
        if dest is None:
            self.log('no dest for export !')
            return

        pi = self.inventree()

        categories = pi.get_category_paths() # TODO find older revs and use their cat
        category_path, ok = QInputDialog.getItem(None, "Select Category", "Category to create the Part", categories)
        if not ok:
            return

        # if root_obj is DBLink : ???

        # root obj is in inventree
        if pi.get_part(ipn=root_obj.PlumeIPN, version=root_obj.PlVersion, revision=root_obj.PlRevision) is not None:
            self.log(f'root IPN/ver.rev already exists : {root_obj.PlumeIPN}, {root_obj.PlVersion}.{root_obj.PlRevision}')
            QMessageBox.warning(None, "ERROR", f'root IPN/ver.rev already exists : {root_obj.PlumeIPN}, {root_obj.PlVersion}.{root_obj.PlRevision}')
            return

        # check that all childrens objects are valid and registered in Inventree : 
        flight_check = True
        err = ""
        for _, p in self.get_children_objects(root_obj):
            if pi.get_part(ipn=p.PlumeIPN, version=p.PlVersion, revision=p.PlRevision) is None:
                flight_check = False
                err += f'IPN/ver.rev is not in Inventree : {p.PlumeIPN}, {p.PlVersion}.{p.PlRevision}\n'

        if not flight_check:
            self.log(err)
            QMessageBox.warning(None, "ERROR", err)
            return


        # create a BOM.
        bom = None

        if root_obj.PlType in ["MechanicalAssembly", "FrameForgeAssembly"]:  # TODO what about frameforge object ? are they assembly ?
            bom = {}
            bom_subobjects = defaultdict(list)

            for ref_id, p in self.get_children_objects(root_obj):
                sub_part = pi.get_part(ipn=p.PlumeIPN, version=p.PlVersion, revision=p.PlRevision)
                bom_subobjects[sub_part.pk].append(ref_id)

            for sub_pk in bom_subobjects:
                tot = len(bom_subobjects[sub_pk])
                refs = bom_subobjects[sub_pk]

                bom[sub_pk] = (tot, refs)

            # case for frameforge profiles
            if root_obj.PlType == "FrameForgeAssembly":  # TODO what about frameforge object ? are they assembly ?
                profiles_data = []
                links_data = []
                traverse_assembly(
                    profiles_data, links_data, root_obj, full_parent_path=False
                )

                profiles = defaultdict(list)
                for p in profiles_data:
                    key = (p["family"], p["material"], p["size_name"])
                    fam, mat, sizename = key
                    prof_ipn = f"{fam.upper()}_{mat[:5].upper()}_{sizename}".replace(" ", "_")
                    profiles[prof_ipn].append((p['ID'], float(p['length'])))

                for prof_ipn in profiles:
                    prof_part = pi.get_part(prof_ipn, "#", "#")
                    if prof_part is None:
                        prof_category_path, ok = QInputDialog.getItem(None, f"Select Category", f"Category to create the profile :\n {prof_ipn}", categories)
                        if not ok:
                            self.log('cancelled by user')
                            return

                        prof_part = pi.create_part(
                            prof_ipn,
                            f"Profile {fam} {mat} {sizename}",
                            "",
                            "#.#",
                            component=True,
                            assembly=False,
                            purchaseable=True,
                            salable=False,
                            virtual=False,
                            category_path=prof_category_path,
                            units = 'mm'
                        )

                    total_length = sum([p[1] for p in profiles[prof_ipn]])
                    refs = [p[0] for p in profiles[prof_ipn]]

                    bom[prof_part.pk] = (total_length, refs)

        # commit
        if not root_obj.PlDatabaseLink and repo_config['export_in_svn']:
            svn.add(dest)
            svn.commit(f"Add export for {root_obj.Document.FileName}", [dest])
                
        # push to Inventree
        pi.create_part(
            root_obj.PlumeIPN,
            root_obj.Label,
            root_obj.PlDescription,
            f"{root_obj.PlVersion}.{root_obj.PlRevision}",
            component=True,
            assembly=root_obj.PlType in ["MechanicalAssembly", "FrameForgeAssembly"],
            purchaseable=root_obj.PlSourcing == "Purchased",
            salable=False,
            virtual=root_obj.PlVirtual,
            attachment_folder=dest if ((not root_obj.PlDatabaseLink) and repo_config['export_in_inventree']) else None,
            category_path=category_path,
            bom=bom
        )

Gui.addCommand("Plume_InitializeObject", InitializePlumeObjectCommand())
Gui.addCommand("Plume_EditExportedObjects", EditExportedObjectsCommand())
Gui.addCommand("Plume_BuildExportedFilesCommand", BuildExportedFilesCommand())
Gui.addCommand("Plume_PublishPartCommand", PublishPartCommand())
