import os
import shutil
import json
import tempfile
import sys
import zipfile

from PySide.QtWidgets import QInputDialog
import FreeCAD as App

def prepare_folder_for_export(start_path):
    """
    return a list of temp files, renamed for inventree export
    """
    temp_dir = tempfile.mkdtemp()
    for root, dirs, files in os.walk(start_path):
        for file in files:
            abs_path = os.path.abspath(os.path.join(root, file))
            file_name = os.path.relpath(abs_path, start=start_path).replace(os.sep, "__")

            shutil.copy(abs_path, os.path.join(temp_dir, file_name))

    l = []
    for root, dirs, files in os.walk(temp_dir):
        for file in files:
            abs_path = os.path.abspath(os.path.join(root, file))
            l.append(abs_path)
        
    return l



def create_thumbnail(input_file, output_dir):
    # Read compressed file
    zfile = zipfile.ZipFile(input_file)
    files = zfile.namelist()

    # Check whether we have a FreeCAD document
    if "Document.xml" not in files:
        print(input_file, " doesn't look like a FreeCAD file")
        return None

    # Read thumbnail from file or use default icon
    image = "thumbnails/Thumbnail.png"
    if image in files:
        image = zfile.read(image)

        # Write icon to output_file
        thumb = open(os.path.join(output_dir, "Thumbnail.png"), "wb")
        thumb.write(image)
        thumb.close()



def read_repo_config(wc):
    try:
        with open(os.path.join(wc, ".plume.json")) as fd:
            data = json.load(fd)

            for k in  ["inventree_url", "plume_ipn_autogenerated", "export_in_inventree", "export_in_svn", "svn_export_mode", "svn_export_rootfolder", "svn_export_subfolder"]:
                if k not in data:
                    raise KeyError(f'Key not present: {k}')

    except IOError:
        data = {
            "inventree_url":"",
            "plume_ipn_autogenerated":True,
            "export_in_inventree":True,
            "export_in_svn":False,
            "svn_export_mode":"subfolder",
            "svn_export_rootfolder":"",
            "svn_export_subfolder":"exports"
        }

    return data

def write_repo_config(wc, data):
    for k in  ["inventree_url", "plume_ipn_autogenerated", "export_in_inventree", "export_in_svn", "svn_export_mode", "svn_export_rootfolder", "svn_export_subfolder"]:
        if k not in data:
            raise KeyError(f'Key not present: {k}')

    with open(os.path.join(wc, ".plume.json"), "w") as fd:
        json.dump(data, fd, indent=4)



def is_fastener(obj):
    return hasattr(obj, "Invert") and hasattr(obj, "Type") and obj.Type !=""

def get_fastener_name(obj):
    if not is_fastener(obj):
        return "Unknown"

    fastener_type = obj.Type
    dia = getattr(obj, "Diameter", "")
    material = getattr(obj, "Material", "")
    length = getattr(obj, 'Length', '') if getattr(obj, 'Length', '') != "Custom" else str(getattr(obj, 'LengthCustom', '')).replace(" mm", "")
    name = ''.join([char for char in obj.Name if not char.isdigit()])

    return f"{name}_{fastener_type}_{dia}_{length}_{material}"
    

def get_ipn_suggestion(obj):
    try:
        path = obj.Document.FileName
        rootpath, subpath = path.split("/trunk/")
        _, project = os.path.split(rootpath)
        (subpath, filename) = os.path.split(subpath)


        subname = "_".join([sp[:4].upper() for sp in subpath.split(os.sep)])
        filename, _ = os.path.splitext(filename)

        return f"{project[:6].upper()}_{subname}_{filename[5:].upper()}"

    except:
        return ""