from inventree.api import InvenTreeAPI
from inventree.part import Part, PartCategory, BomItem

from freecad.plume.utils.fc_utils import prepare_folder_for_export

class PlumeInventree(object):
    """
    About link between Plume/Freecad and Inventree.
    PlumeIPN are linked to IPN in Inventree. (it needs to allow multiple IPN)

    PlumeIPN are unique, autogenerated via a UUID or 
    (?) chosen by the user and check against the Inventree Server before creating the PlumeObject

    Shall we keep a valid list in the repository as well, of all the IPN used ?
    """
    _instance = None

    @classmethod
    def instance(cls):
        if cls._instance is None:
            # TODO : guess adress from SVN address, and token... ?
            adress = ""
            token = ""

            cls._instance = cls(adress, token, strict)
        return cls._instance

    def __init__(self, adress, token=None, username=None, password=None, strict=True):
        self.api = InvenTreeAPI(adress, token=token, username=username, password=password, strict=strict)

    def get_category_paths(self):
        categories = PartCategory.list(self.api)
        return [c.pathstring for c in categories]

    def is_ipn_available(self, ipn):
        return len(Part.list(self.api, IPN=ipn)) == 0

    def get_parts(self, ipn=None, active=True):
        return Part.list(self.api, IPN=ipn, active=active)

    def get_part(self, ipn, version, revision):
        parts = Part.list(self.api, IPN=ipn, revision=f"{version}.{revision}")
        if len(parts) == 0:
            return None
        elif len(parts) == 1:
            return parts[0]
        else:
            raise Exception('error')

    def create_part(self,
        ipn, name, description, revision, 
        component, assembly, purchaseable, salable, virtual,
        attachment_folder = None,
        category_path = None,
        bom = None
    ):
        data = {
            "IPN":ipn,
            "name":name,
            "description":description,
            "revision":revision,
            "component":component,
            "assembly":assembly,
            "purchaseable":purchaseable,
            "salable":salable,
            "virtual":virtual
        }

        # get the category
        if category_path is not None:
            categories = [c for c in PartCategory.list(self.api) if c.pathstring == category_path]
            if len(categories) == 1:
                cat = categories.pop()
                data['category'] = cat.pk
            else:
                raise Exception("ERROR")


        #try to get the last Part created with this IPN
        last_parts = Part.list(self.api, IPN=ipn, has_revisions=False)
        if len(last_parts) == 1:
            last_part = last_parts.pop()
            data['revision_of'] = last_part.pk
        elif len(last_parts) > 1:
            raise Exception("ERROR")

        part = Part.create(self.api, data=data)

        # bom
        if bom is not None:
            for k in bom:
                refs = bom [k]
                BomItem.create(self.api, data={'part':part.pk, 'sub_part':k, 'quantity':len(refs), 'reference':', '.join(refs)})


        # upload attachment
        if attachment_folder is not None:
            for path in prepare_folder_for_export(attachment_folder):
                part.uploadAttachment(path)

        return part
