import os
from PySide import QtWidgets, QtCore

from PySide6.QtCore import QModelIndex
from PySide.QtWidgets import QDialog, QGridLayout, QComboBox, QListWidget, QPushButton, QFileDialog, QDialogButtonBox, QListWidgetItem, QCheckBox, QTextEdit, QLabel,  QWidget, QTreeView, QListView, QVBoxLayout, QHBoxLayout
from PySide.QtGui import QBrush, QColorConstants, QColor, QIcon

import FreeCAD as App
import FreeCADGui as Gui

from freecad.plume.pl_tools import UIPATH, ICONPATH, TRANSLATIONSPATH, translate
from freecad.plume.utils.svnfilesystemmodel import SVNFileSystemModel
from freecad.plume.utils.selector import PlumeSelection

from freecad.plume.utils.plume_svn import PlumeSvn
from freecad.plume.utils.fc_utils import read_repo_config, write_repo_config

class ManageSubversionWorkingCopiesDialog(QDialog):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        param = App.ParamGet("User parameter:BaseApp/Preferences/Plume")
        if not param.IsEmpty():
            wcp = param.GetString("WorkingCopy Available Paths").split(';')

        self.setWindowTitle('SVN Working Copies')
        # self.setWindowIcon(QIcon('./assets/wishlist.png'))
        # self.setGeometry(100, 100, 400, 100)

        layout = QGridLayout(self)
        self.setLayout(layout)

        self.list_widget = QListWidget(self)
        self.list_widget.addItems(wcp)
        layout.addWidget(self.list_widget, 0, 0, 4, 1)

        # create buttons
        add_button = QPushButton('Add')
        add_button.clicked.connect(self.add)

        remove_button = QPushButton('Remove')
        remove_button.clicked.connect(self.remove)

        clear_button = QPushButton('Clear')
        clear_button.clicked.connect(self.clear)

        layout.addWidget(add_button, 0, 1)
        layout.addWidget(remove_button, 2, 1)
        layout.addWidget(clear_button, 3, 1)

        buttonBox = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        buttonBox.accepted.connect(self.accept)
        buttonBox.rejected.connect(self.reject)

        layout.addWidget(buttonBox, 4, 0)

        # show the window
        self.show()

    def add(self):
        text = QFileDialog.getExistingDirectory(None, "Select Directory", "")
        if text:
            self.list_widget.addItem(text)

    def remove(self):
        current_row = self.list_widget.currentRow()
        if current_row >= 0:
            current_item = self.list_widget.takeItem(current_row)
            del current_item

    def clear(self):
        self.list_widget.clear()

    def accept(self):
        paths = [self.list_widget.item(x).text() for x in range(self.list_widget.count())]

        param = App.ParamGet("User parameter:BaseApp/Preferences/Plume")
        param.SetString("WorkingCopy Available Paths", ";".join(paths))
        # param.SetString("CurrentWorkingCopy", selected_path)

        return super().accept()



class RepositoryPreferencesDialog(QDialog):
    def __init__(self, working_copy):
        super().__init__()
        self.initialize_ui()

        self.working_copy = working_copy
        self.read_config()

    def read_config(self):
        data = read_repo_config(self.working_copy)

        self.title_label.setText(f"Repo {self.working_copy}")
        self.inventree_server_le.setText(data.get('inventree_url', ''))
        self.plume_ipn_autogenerated_cb.setChecked(data.get('plume_ipn_autogenerated'))

        self.export_in_inventree_cb.setChecked(data.get('export_in_inventree'))
        self.export_in_svn_cb.setChecked(data.get('export_in_svn'))

        self.svn_subfolder_rb.setChecked(data.get('svn_export_mode') == "subfolder")
        self.svn_rootfolder_rb.setChecked(data.get('svn_export_mode') == "rootfolder")

        self.svn_export_rootfolder_le.setText(data.get('svn_export_rootfolder'))
        self.svn_export_subfolder_le.setText(data.get('svn_export_subfolder'))

    def initialize_ui(self):
        vl = QtWidgets.QVBoxLayout()
        hl = QtWidgets.QHBoxLayout()

        self.title_label = QtWidgets.QLabel()
        self.title_label.setText("Repo ")
        vl.addWidget(self.title_label)
        
        label = QtWidgets.QLabel()
        label.setText(translate("RepositoryPreferencesDialog", "Inventree Server"))
        hl.addWidget(label)

        self.inventree_server_le = QtWidgets.QLineEdit()
        hl.addWidget(self.inventree_server_le)

        vl.addLayout(hl)

        self.plume_ipn_autogenerated_cb = QCheckBox()
        self.plume_ipn_autogenerated_cb.setText("Auto-generate (UUID) PlumeIPN")
        vl.addWidget(self.plume_ipn_autogenerated_cb)

        gb = QtWidgets.QGroupBox()
        gb.setTitle(translate("RepositoryPreferencesDialog", "Exports"))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(gb.sizePolicy().hasHeightForWidth())
        
        gb.setSizePolicy(sizePolicy)
        gl = QtWidgets.QGridLayout(gb)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        gl.addItem(spacerItem, 4, 0, 1, 1)

        self.svn_export_subfolder_le = QtWidgets.QLineEdit(parent=gb)
        gl.addWidget(self.svn_export_subfolder_le, 2, 1, 1, 1)

        self.export_in_inventree_cb = QtWidgets.QCheckBox(parent=gb)
        self.export_in_inventree_cb.setText(translate("RepositoryPreferencesDialog", "Export builds in InvenTree"))
        gl.addWidget(self.export_in_inventree_cb, 0, 0, 1, 1)

        self.svn_rootfolder_rb = QtWidgets.QRadioButton(parent=gb)
        self.svn_rootfolder_rb.setText(translate("RepositoryPreferencesDialog", "Export in specific root folder"))
        gl.addWidget(self.svn_rootfolder_rb, 3, 0, 1, 1)

        self.svn_subfolder_rb = QtWidgets.QRadioButton(parent=gb)
        self.svn_subfolder_rb.setText(translate("RepositoryPreferencesDialog", "Export in subfolder of release"))
        gl.addWidget(self.svn_subfolder_rb, 2, 0, 1, 1)

        self.svn_export_rootfolder_le = QtWidgets.QLineEdit(parent=gb)
        gl.addWidget(self.svn_export_rootfolder_le, 3, 1, 1, 1)

        self.export_in_svn_cb = QtWidgets.QCheckBox(parent=gb)
        self.export_in_svn_cb.checkStateChanged.connect(self.export_in_inventree_changed)
        self.export_in_svn_cb.setText(translate("RepositoryPreferencesDialog", "Export builds in SVN"))
        gl.addWidget(self.export_in_svn_cb, 1, 0, 1, 1)

        vl.addWidget(gb)

        buttonBox = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        buttonBox.accepted.connect(self.accept)
        buttonBox.rejected.connect(self.reject)

        vl.addWidget(buttonBox)
        self.setLayout(vl)


    def export_in_inventree_changed(self, state):
        en = state == QtCore.Qt.Checked
        self.svn_subfolder_rb.setEnabled(en)
        self.svn_rootfolder_rb.setEnabled(en)
        self.svn_export_rootfolder_le.setEnabled(en)
        self.svn_export_subfolder_le.setEnabled(en)


    def accept(self):
        data = {
            "inventree_url":self.inventree_server_le.text(),
            "plume_ipn_autogenerated":self.plume_ipn_autogenerated_cb.isChecked(),
            "export_in_inventree":self.export_in_inventree_cb.isChecked(),
            "export_in_svn":self.export_in_svn_cb.isChecked(),
            "svn_export_mode":"subfolder" if self.svn_subfolder_rb.isChecked() else "rootfolder",
            "svn_export_rootfolder": self.svn_export_rootfolder_le.text(),
            "svn_export_subfolder":self.svn_export_subfolder_le.text()
        }

        write_repo_config(self.working_copy, data)
        super().accept()


class CommitListWidget(QListWidget):
    COLOR_MAP = {
        "modified": QColor("#0066cc"),
        "added": QColor("#009900"),
        "deleted": QColor("#cc0000"),
        "conflicted": QColor("#ff6600"),
        "missing": QColor("#990099"),
        "unversioned": QColor("#808080"),
    }

    def addFile(self, path, status):
        item = QListWidgetItem(path)
        item.setCheckState(QtCore.Qt.Unchecked)
        if status in self.COLOR_MAP:
            item.setForeground(QBrush(self.COLOR_MAP[status]))
        self.addItem(item)

    def getSelectedPaths(self):
        return [self.item(x).text() for x in range(self.count()) if self.item(x).checkState() == QtCore.Qt.Checked]


class CommitDialog(QDialog):
    def __init__(self, paths, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.setWindowTitle('SVN Commit')

        layout = QGridLayout(self)
        self.setLayout(layout)

        self.list_widget = CommitListWidget(self)
        for s, p in paths:
            self.list_widget.addFile(p, s)

        layout.addWidget(QLabel('Files to commit', self), 0, 0)
        layout.addWidget(self.list_widget, 1, 0)

        layout.addWidget(QLabel('Commit Message', self), 2, 0)
        self.text_edit = QTextEdit(self)
        layout.addWidget(self.text_edit, 3, 0)


        buttonBox = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        buttonBox.accepted.connect(self.accept)
        buttonBox.rejected.connect(self.reject)

        layout.addWidget(buttonBox, 4, 0)

    def accept(self):
        commit_msg = self.text_edit.toPlainText()
        paths_to_commit = self.list_widget.getSelectedPaths()

        if commit_msg == "" or len(paths_to_commit) == 0:
            return False

        super().accept()

    @staticmethod
    def get_commit_infos(paths):
        dialog = CommitDialog(paths)
        retcode = dialog.exec_()

        paths_to_commit = dialog.list_widget.getSelectedPaths()
        commit_msg = dialog.text_edit.toPlainText()

        return retcode == 1, paths_to_commit, commit_msg



class DeselectableTreeView(QTreeView):
    def mousePressEvent(self, event):
        self.clearSelection()
        QTreeView.mousePressEvent(self, event)

class MainWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.model = SVNFileSystemModel()

        self.tree = DeselectableTreeView()
        self.tree.setModel(self.model)
        self.tree.selectionModel().selectionChanged.connect(self.onTreeSelectionChanged)
        self.tree.doubleClicked.connect(self.onTreeItemDoubleClicked)


        self.workingcopies_combobox = QComboBox()
        self.refreshWorkingCopies()
        param = App.ParamGet("User parameter:BaseApp/Preferences/Plume")
        self.workingcopies_combobox.activated.connect(lambda index : self.setRootDir(self.workingcopies_combobox.currentText()))
        if not param.IsEmpty():
            curr_wc = param.GetString("CurrentWorkingCopy")
            if curr_wc:
                index = self.workingcopies_combobox.findText(curr_wc)
                if curr_wc != -1:
                    self.workingcopies_combobox.setCurrentIndex(index)
                    self.setRootDir(curr_wc)

        self.refreshButton = QPushButton('Refresh')
        self.refreshButton.clicked.connect(self.refresh)


        menu_layout = QHBoxLayout()
        menu_layout.addWidget(self.workingcopies_combobox)
        menu_layout.addWidget(self.refreshButton)
        menu_widget = QWidget()
        menu_widget.setLayout(menu_layout)

        l = QVBoxLayout()
        l.addWidget(menu_widget)
        l.addWidget(self.tree)

        self.setLayout(l)

    def onClose(self): # TODO
        PlumeSelection.instance().resetTreeSelection()
        
    def refreshWorkingCopies(self):
        self.workingcopies_combobox.clear()

        param = App.ParamGet("User parameter:BaseApp/Preferences/Plume")
        if not param.IsEmpty():
            wcp = param.GetString("WorkingCopy Available Paths").split(';')

        self.workingcopies_combobox.addItems(wcp)
        PlumeSelection.instance().resetTreeSelection()

    def setRootDir(self, path):
        param = App.ParamGet("User parameter:BaseApp/Preferences/Plume")
        if param.IsEmpty() or (param.GetString("CurrentWorkingCopy") != path):
            param.SetString("CurrentWorkingCopy", path)

        root_index = self.model.setRootPath(path)
        self.tree.setRootIndex(root_index)
        PlumeSelection.instance().resetTreeSelection()

        self.refresh()

    def onTreeSelectionChanged(self, selected, deselected):
        selector = PlumeSelection.instance()

        indexes = selected.indexes()
        if len(indexes) == 0:
            selector.resetTreeSelection()
        else:
            path = self.model.filePath(indexes[0])
            selector.setTreeSelection([path])

    def refresh(self):
        root_path = self.model.rootPath()
        PlumeSelection.instance().resetTreeSelection()

        ps = PlumeSvn(root_path)
        for s in ps.status(".", verbose=True):
            self.model.setSVNInfo(s)

    def onTreeItemDoubleClicked(self, index):
        path = self.model.filePath(index)

        App.openDocument(path)


def open_or_create_directory(log_dir, caption=""):
    """
    open or create a directory
    """

    dialog = QtWidgets.QFileDialog(None, caption=caption)
    dialog.setOption(QtWidgets.QFileDialog.DontUseNativeDialog, True)
    dialog.setDirectory(log_dir)
    dialog.setFileMode(QtWidgets.QFileDialog.Directory)
    dialog.setOption(QtWidgets.QFileDialog.ShowDirsOnly, True)
    dialog.setLabelText(QtWidgets.QFileDialog.Accept, "Select")
    if dialog.exec_() == QtWidgets.QFileDialog.Accepted:
        directories = dialog.selectedFiles()
        if len(directories) != 1:
            raise ValueError("can't get more than one dir selected")

        return directories[0]

    return None